name: Check for file updates

on:
  schedule:
    - cron: '0 */4 * * *'  # 这将在每 4 小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  check-updates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Download file
      run: |
        wget -O new_ilist.txt ${{ secrets.PRIVATE_URL }}
        wget -O new_release_ilist.txt https://cdn.megagamelog.com/cross/release/ilist.txt

    - name: Compare files
      id: diff
      run: |
        if diff new_ilist.txt ilist.txt > /dev/null 2>&1; then
          echo "::set-output name=changed::false"
        else
          echo "::set-output name=changed::true"
        fi

    - name: Check release ilist
      id: diff_release
      run: |
        if diff new_release_ilist.txt r_ilist.txt > /dev/null 2>&1; then
          echo "::set-output name=changed::false"
        else
          echo "::set-output name=changed::true"
        fi

    - name: Compare ilist
      id: diff_new
      if: steps.diff_release.outputs.changed == 'true'
      run: |
        if diff new_ilist.txt new_release_ilist.txt > /dev/null 2>&1; then
          echo "::set-output name=changed::false"
        else
          echo "::set-output name=changed::true"
        fi

    - name: Update file
      if: steps.diff.outputs.changed == 'true'
      run: |
        mv new_file.txt ilist.txt
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update file"
        git push

    - name: Create issue if release ilist changed
      if: steps.diff_release.outputs.changed == 'true'
      uses: actions/github-script@v5
      with:
        script: |
          const fs = require('fs');
          const issueTitle = "Official release ilist.txt changed";
          let issueBody = `**new_release_ilist.txt:**\n\n\`\`\`\n${fs.readFileSync('new_release_ilist.txt', 'utf8')}\n\`\`\``;
          if (steps.diff_new.outputs.changed == 'true') {
            issueBody += `\n\n**new_ilist.txt:**\n\n\`\`\`\n${fs.readFileSync('new_ilist.txt', 'utf8')}\n\`\`\``;
          }
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: issueTitle,
            body: issueBody
          });